### ISSUE TITLE
Livestream: Exploring Public APIs and the Public API Network

### ISSUE THREAD

**Issue by pmmistry** [postmanlabs/devrel-content#316] opened 2022-09-13 18:17 UTC
### Describe the content you'd like to see

Exploring Public APIs and the Public API Network
Pooja & Deepa 

In this week's Postman Live, Pooja has invited Postman’s Lead Product Manager Strategist Deepa Goyal to discuss all things Public APIs. Together they will explore the benefits of having Public APIs , what factors to consider when creating them and how to be a part of the Postman Public API network. 

Happening on 2022-09-29T15:00:00.000Z

### Content Type

Talk

### If the request is for a video, indicate which type

Livestream

**Comment by pmmistry** [comment] 2022-09-13 18:17
@Kcorb95 could you please add this as event on restream / youtube

**Comment by arlemi** [comment] 2022-09-20 08:51
Duplicate of #317 - let's use the automatically generated issues for livestream, saves us from creating them.

**Closed by arlemi** 2022-09-20 08:51 UTC
Labels: talk, content, livestream
