### ISSUE TITLE
Livestream: Automating YouTube Analytics: Data Processing & Integration with Postman Flows

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#648] opened 2023-09-21 21:45 UTC
### Describe the content you'd like to see

In this week's Postman LIVE, Ian and Kevin picking up with part two of our new series that takes us through building an entire project from scratch using Postman. Follow along as we transition from gathering YouTube Analytics to dynamically populating Google Sheets. In this session, discover the power of Postman Flows as we integrate with the Google Sheets API. Come along as we transform raw YouTube data into actionable insights, setting the stage for our final chapter in this engaging three-part series.

Check out part one of the series here:
https://youtu.be/JtPvRA94FjY

Get notified when Postman goes live by following us on YouTube!
https://www.youtube.com/@postman

Contact us:
If you have questions or comments about any Postman features, pricing, or anything else, our team is always ready. Visit our Support Center to get started:
https://www.postman.com/support

Please familiarize yourself with the Postman Community code of conduct.
https://www.postman.com/legal/community-code-of-conduct/

Happening on 2023-10-05T15:00:00.000Z

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by Kcorb95** [comment] 2023-10-16 20:49
Duplicate of https://github.com/postmanlabs/devrel-content/issues/655

**Closed as completed by Kcorb95** 2023-10-16 20:49 UTC
Labels: video, content, livestream
