### ISSUE TITLE
Livestream: How We Made It: server-side events

### ISSUE THREAD

**Issue by iandouglas** [postmanlabs/devrel-content#476] opened 2023-03-03 22:02 UTC
### Describe the content you'd like to see

Scheduled for Thursday March 9

### Content Type

Video, Talk

### If the request is for a video, indicate which type

Livestream

**Comment by arlemi** [comment] 2023-03-06 11:25
Duplicate of #475 (issues for livestream get automatically created from Airtable)

**Closed as not planned by arlemi** 2023-03-06 11:25 UTC
Labels: video, talk, content, livestream, events
