### ISSUE TITLE
Livestream : How We built it : Postman CLI 

### ISSUE THREAD

**Issue by pmmistry** [postmanlabs/devrel-content#447] opened 2023-02-09 21:25 UTC
### Describe the content you'd like to see

How we built it session with Malvika - Feb 23 : https://docs.google.com/document/d/1gohFL-xtW0B_rWwZC3Xjpgy6xpIMtyCCK72Dn-o7y0Y/edit

### Content Type

Talk

### If the request is for a video, indicate which type

None

**Comment by arlemi** [comment] 2023-02-13 10:12
Duplicate of #449. 

@pmmistry the issues for Livestreams and Intergalactic are created automatically. 👍

**Closed as not planned by arlemi** 2023-02-13 10:12 UTC
Labels: talk, content, livestream
